python train_system.py \
--model_name_or_path /home/dongfangxu/Projects/models/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext \
--data_dir /home/dongfangxu/Projects/SSN_Drug_Normalization/data/bert/ner/smm4h20+_smallset/ \
--output_dir /home/dongfangxu/Projects/SSN_Drug_Normalization/data/models/ner_test_smallset/ \
--task_name smm4h_ner \
--do_train \
--do_eval \
--do_predict \
--learning_rate 5e-5 \
--per_device_train_batch_size 16 \
--max_seq_length 128 \
--num_train_epochs 5 \
--overwrite_output_dir true \
--overwrite_cache true